name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Test-And-Build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3 python3-pip scons git openocd gcc build-essential pyenv libboost-all-dev openocd stlink-tools libgtest-dev pipenv wget -y
      - run: wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
      - run: tar -xf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
      - run: mv gcc-arm-none-eabi-10.3-2021.10 ~/
      - run: echo 'export PATH="~/gcc-arm-none-eabi-10.3-2021.10/bin:$HOME/.local/bin:$PATH:$PATH"' >> ~/.bashrc
      - run: source ~/.bashrc
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd fang-mcb-project
      - run: pipenv install --python 3.8.10
      - run: pipenv run scons build
      - run: pipenv run scons test
 
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
